export default {
  RECEIVE_DATA: "RECEIVE_DATA",
  SUBSCRIBE_TO_DATA: "SUBSCRIBE_TO_DATA",
  UNSUBSCRIBE_FROM_DATA: "UNSUBSCRIBE_FROM_DATA",
  SELECT_PAIR: "SELECT_PAIR",
  SET_AVAILABLE_PAIRS: "SET_AVAILABLE_PAIRS",
};
