export default {
  RECEIVE_DATA: "RECEIVE_DATA",
  SUBSCRIBE_TO_DATA: "SUBSCRIBE_TO_DATA",
  UNSUBSCRIBE_FROM_DATA: "UNSUBSCRIBE_FROM_DATA",
  SET_UNSUBSCRIBE_ID: "SET_UNSUBSCRIBE_ID",
  SELECT_PAIR: "SELECT_PAIR",
};
